ft emailverification 176153405
atlp-rwanda/runners-bn-backend pull request #10
Opened 2021-01-19 19:09 UTC by unadine

## What does this PR do?
Email verification upon successful signup

## Description of Task to be completed?
User should be able to receive a verification link via email upon successful signup

## How should this be manually tested?
npm run test

## Any background context you want to provide?

## What are the relevant pivotal tracker stories?

## Screenshots (if appropriate)

## Questions:

2021-02-08 08:09 UTC, James-nyagatare approved these changes
LGTM @unadine

2021-02-08 08:09 UTC, James-nyagatare commented on src/middlewares/auth.js
> +  static reqParamsAuth(req, res, next) {
Good variable naming.

2021-02-08 08:11 UTC, James-nyagatare commented
@unadine  squash the commits into one

2021-02-08 09:28 UTC, harerakalex requested changes
Great job @unadine however, consider the below comment.

2021-02-08 09:28 UTC, harerakalex commented on src/controllers/userController.js
> +      return Response.success(res, code.ok, 'You have been verified!', { firstName, lastName });
This data `firstName and lastName` that you are sending in response is not that necessary, It will be great if you send only a message.

2021-03-13 07:55 UTC, Mucyo-Aime-Christian commented on src/tests/user.test.js
> +  });
please consider removing this unnecessary console

2021-03-13 07:59 UTC, Mucyo-Aime-Christian commented on src/tests/user.test.js
> +  });
how is this supposed to be 401 ??

2021-03-13 08:02 UTC, Mucyo-Aime-Christian reviewed
well done @unadine, however, mind to work on feedbacks i left

2021-03-14 21:26 UTC, unadine commented on src/tests/user.test.js
> +  });
it is passing an invalid token

2021-03-16 08:45 UTC, Mucyo-Aime-Christian approved these changes
LGTM

2021-03-16 09:05 UTC, harerakalex approved these changes
LGTM

2021-03-16 09:05 UTC, merged