feature(signup and signin): signin using passport
atlp-rwanda/runners-bn-backend pull request #13
Opened 2021-01-21 06:52 UTC by Mucyo-Aime-Christian

## What does this PR do?

- signup
- signin with passport localStrategy
- tests and document all endpoints

## Description of Task to be completed?

- signup and get token
- signin and get token

## How should this be manually tested?

- start server by npm run dev command
- then test with swagger or postman

## Any background context you want to provide?

- N/A

## What are the relevant pivotal tracker stories?

- https://www.pivotaltracker.com/story/show/176153401

## Screenshots (if appropriate)

- N/A

2021-01-21 08:00 UTC, James-nyagatare requested changes

2021-01-21 08:00 UTC, James-nyagatare commented on src/controllers/userController.js
> +// import user from '../database/models/user';
Remove this unnecessary comment

2021-01-21 08:00 UTC, James-nyagatare commented on src/routes/index.js
> +  app.use(`${urlPreffix}/user/`, userRoutes);
Why this route??? I think it will be better if we are stick to /users.

2021-01-21 08:00 UTC, James-nyagatare commented on src/helpers/joiResponse.js
> +      error.details[0].message.replace(/"/g, '')
I think you need to update this to [error.details[0].message.replace(/\"/g, '')] in order to send a clean joi response.

2021-01-21 10:46 UTC, harerakalex requested changes
@Mucyo-Aime-Christian, good start, however, you have to consider working on the following feedback ASAP.

2021-01-21 10:46 UTC, harerakalex commented on .nycrc
> +{"reporter": ["lcov","text"], "exclude": ["src/tests", "src/database", "src/helpers/findUser.js", "src/config/passport.js", "src/helpers/generateToken.js", "src/helpers/mailer/sendMailer.js"]}
@Mucyo-Aime-Christian,  kindly test everything instead of excluding them.

2021-01-21 10:46 UTC, harerakalex commented on package.json
> +    "pretest": "NODE_ENV=test npm run migrate-undo && NODE_ENV=test npm run migrate ",
@Mucyo-Aime-Christian , Why did you remove the seed script, better know why is there before you remove it.

2021-01-21 10:46 UTC, harerakalex commented on src/config/passport.js
> +      const user = await UserService.isUserExist(req.body.email);
@Mucyo-Aime-Christian, I think this not good naming of function `isUserExist` here you should use something like findUser and again this function exist means you should have used this existing service instead of creating yours.

2021-01-21 10:46 UTC, harerakalex commented on src/config/passport.js
> +      return done(null, user.get());
Instead of putting this `get()` here, put it in the user service. @Mucyo-Aime-Christian

2021-01-21 10:46 UTC, harerakalex commented on src/controllers/userController.js
> +// Signup page controller
We already have userController you should have used it by adding your own code.

2021-01-21 10:46 UTC, harerakalex commented on src/controllers/userController.js
> +      return Response.error(res, code.badRequest, 'password mis-Match');
This message should be changed to something like `Password does not match`. And again better use joi validation to handle this.

2021-01-21 10:46 UTC, harerakalex commented on src/controllers/userController.js
> +    if (!firstName || !lastName || !email || !password || !confirmPassword) {
Better use join validation to handle this.

2021-01-21 10:46 UTC, harerakalex commented on src/controllers/userController.js
> +    const rawData = req.body;
Why did you declare `rawData`, I don't think it is needed.

2021-01-21 10:46 UTC, harerakalex commented on src/controllers/userController.js
> +      const obj = new Password(rawData);
Please pass the argument which is only needed by this function which is password.

2021-01-21 10:46 UTC, harerakalex commented on src/controllers/userController.js
> +    if (!email || !password) {
Please use joi for validation

2021-01-21 10:46 UTC, harerakalex commented on src/controllers/userController.js
> +    const rawData = req.body;
Unnecessary variable

2021-01-21 10:46 UTC, harerakalex commented on src/controllers/userController.js
> +      const token = generateToken(rawData);
Make sure you have to  include all needed information in the token.

2021-01-21 10:46 UTC, harerakalex commented on src/controllers/userController.js
> +      const loggedinUser = await models.User.findOne({ where: { email } });
We don't want to see modal usage in the controller, kindly use the service.

2021-01-21 10:46 UTC, harerakalex commented on src/helpers/generatePassword.js
> +  constructor(data) {
You can remove this constructor and create a static member function that will take a password as a parameter.

2021-01-21 10:46 UTC, harerakalex commented on src/config/passport.js
> +const { User } = models;
Remove this line.

2021-01-21 10:46 UTC, harerakalex commented on src/database/models/index.js
> +/* eslint-disable global-require */
You are making so much noise on your PR by doing unnecessary changes. Better avoid having noisy PR.

2021-01-21 10:46 UTC, harerakalex commented on src/database/models/user.js
> +    confirmPassword: {
Not needed at all, we only need password

2021-01-21 10:46 UTC, harerakalex commented on src/helpers/generateToken.js
> +import Response from './sendResponse';
This file was not supposed to be touched.

2021-01-27 16:36 UTC, James-nyagatare requested changes
Weldone @Mucyo-Aime-Christian, Tho consider working on comments I left here.

2021-01-27 16:36 UTC, James-nyagatare commented on src/middlewares/joiValidator.js
> +      confirmPassword: Joi.any().valid(Joi.ref('password')).required().label('Confirm password')
Great idea @Mucyo-Aime-Christian

2021-01-27 16:36 UTC, James-nyagatare commented on src/services/findUser.js
> +import models from '../database/models';
I don't think we need this service we already had one.

2021-01-27 16:36 UTC, James-nyagatare commented on src/controllers/userController.js
> +      const createUser = await models.User.create(req.body);
I think it will much better if you use service to create a user instead of using models in the controller.

2021-01-28 07:00 UTC, harerakalex requested changes
@Mucyo-Aime-Christian you made a good improvement, however, you need to improve your PR a little bit so consider the bellow feedback.

2021-01-28 07:00 UTC, harerakalex commented on .nycrc
> +{"reporter": ["lcov","text"], "exclude": ["src/tests", "src/database","src/config/passport.js" ]}
Exclude all config folder.

2021-01-28 07:00 UTC, harerakalex commented on src/config/passport.js
> +      const userObj = await User.findById(user.id);
Create a service for finding a user by Id. and use it here instead of using model.

2021-01-28 07:00 UTC, harerakalex commented on src/controllers/userController.js
> +      const loggedinUser = await UserService.findUser({ email: req.body.email });
You destructured an email on the top of this function but here you are not using it. Better use it here instead of using `req.body.email`

2021-01-28 07:00 UTC, harerakalex commented on src/controllers/userController.js
> +      const token = generateToken(req.body);
Generate a token when the user is successfully registered.

2021-01-28 07:00 UTC, harerakalex commented on src/controllers/userController.js
> +      const token = generateToken(req.body);
Generate a token when the user is successfully logged in.

2021-01-28 07:00 UTC, harerakalex commented on src/controllers/userController.js
> +      const loggedinUser = await UserService.findUser({ email: req.body.email });
This is not necessary when using a passport. because You have already done in passport config so here use `req.user`.

2021-01-28 07:00 UTC, harerakalex commented on src/controllers/userController.js
> +        id, firstName, lastName, email, managerId, role, createdAt, updatedAt, token
To make this shorter try to send `createdUser` instead of sending those keys.

2021-01-29 13:50 UTC, harerakalex commented on src/helpers/sendResponse.js
> +    console.log(status);
Kindly remove this console from here.

2021-01-29 23:59 UTC, harerakalex approved these changes

2021-01-30 07:33 UTC, James-nyagatare approved these changes

2021-01-30 08:20 UTC, merged