bg(coveralls): Fix coveralls
atlp-rwanda/runners-bn-backend pull request #15
Opened 2021-01-27 18:36 UTC by unadine

## What does this PR do?
Fix coveralls
## Description of Task to be completed?
Add coveralls script 
## How should this be manually tested?
npm run coverage

## Any background context you want to provide?

## What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2481695/stories/176581751

## Screenshots (if appropriate)

## Questions:

2021-02-06 16:46 UTC, James-nyagatare reviewed
LGTM but can you please squash those two commits into 1.

2021-02-17 08:16 UTC, harerakalex commented
@James-nyagatare kindly add `.codeclimate.yml` on this PR.

2021-02-19 09:24 UTC, harerakalex requested changes

2021-02-19 09:24 UTC, harerakalex commented on .codeclimate.yml
> +  - "src/database"
@James-nyagatare exclude also config folder

2021-02-19 13:17 UTC, merged