feat(trip comments): comments  on trips
atlp-rwanda/runners-bn-backend pull request #16
Opened 2021-01-28 15:06 UTC by James-nyagatare

## What does this PR do?
- Adds, retrieves, delete comment on a trip
## Description of Task to be completed?
```
- Adds comment on a trip
- Retrieves all comments on a trip thread
- Deletes a comment
```
## How should this be manually tested?
```
- Fetch the branches using git fetch
- Test it using postman
```
## Any background context you want to provide?
- N/A
## What are the relevant pivotal tracker stories?
- [Story](https://www.pivotaltracker.com/story/show/176153408)
## Screenshots (if appropriate)
- N/A
## Questions:
-N/A

2021-02-02 08:25 UTC, unadine reviewed
all good

2021-02-02 21:14 UTC, Mucyo-Aime-Christian commented on src/controllers/commentController.js
> +      return Response.success(res, 201, 'Comment successfuly added', commented);
try to use our usual way of sending status instead of just number

2021-02-02 21:17 UTC, Mucyo-Aime-Christian commented on src/controllers/commentController.js
> +* @description this method adds a comment to a trip
try to use relevant description comment

2021-02-02 21:18 UTC, Mucyo-Aime-Christian commented on src/controllers/commentController.js
> +* @description this method adds a comment to a trip
same here

2021-02-02 21:22 UTC, Mucyo-Aime-Christian commented on src/services/commentServices.js
> +* @description this method adds a comment to a trip
checkout all your description message please

2021-02-02 21:24 UTC, Mucyo-Aime-Christian reviewed
well done @James-nyagatare however, check if you can implement feedbacks that i left.

2021-02-03 05:17 UTC, James-nyagatare commented on src/services/commentServices.js
> +* @description this method adds a comment to a trip
@Mucyo-Aime-Christian  all resolved. please recheck

2021-02-03 07:14 UTC, Mucyo-Aime-Christian reviewed
Good work @James-nyagatare  now it LGTM.

2021-02-03 12:47 UTC, harerakalex requested changes
Well done @James-nyagatare, kindly consider the following comments

2021-02-03 12:47 UTC, harerakalex commented on src/controllers/commentController.js
> +      if (role !== roles.REQUESTER && role !== roles.MANAGER) return Response.error(res, code.forbidden, 'forbidden!');
@James-nyagatare, Create a middlware to handle this condion.

2021-02-03 12:47 UTC, harerakalex commented on src/controllers/commentController.js
> +      if (id !== trip.userId && id !== trip.managerId) return Response.error(res, code.forbidden, 'forbidden!');
Better here also create a specific middleware to handle this.

2021-02-03 12:47 UTC, harerakalex commented on src/controllers/commentController.js
> +      if (role !== roles.REQUESTER && role !== roles.MANAGER) return Response.error(res, code.forbidden, 'forbidden!');
I think now you see that this condition is being repeated.

2021-02-03 12:47 UTC, harerakalex commented on src/services/commentServices.js
> +      return data;
Make sure you do not return dataValue.

2021-02-03 12:47 UTC, harerakalex commented on src/services/commentServices.js
> +const userInc = {
What did you mean by `userInc` better name a well descriptive variable?

2021-02-04 08:41 UTC, harerakalex approved these changes

2021-02-04 08:42 UTC, merged