Ft accommodation 176153390
atlp-rwanda/runners-bn-backend pull request #17
Opened 2021-02-05 12:15 UTC by Mucyo-Aime-Christian

## What does this PR do?

- allow the users to interact with accommodations

## Description of Task to be completed?

- create, delete, update, view accommodations
- tests all the accommodation endpoints with mocha
- document endpints with swagger 

## How should this be manually tested?

- clone the Repository 
- use postman or swagger 
- run command ***npm run dev***

## Any background context you want to provide?

- N/A

## What are the relevant pivotal tracker stories?

- https://www.pivotaltracker.com/story/show/176153390

## Screenshots (if appropriate)

- N/A

## Questions:
no questions

2021-02-09 06:40 UTC, James-nyagatare requested changes
Weldone @Mucyo-Aime-Christian, consider implementing the feedbacks I left tho.

2021-02-09 06:40 UTC, James-nyagatare commented on src/database/models/user.js
> -      User.hasMany(models.Trip, {
@Mucyo-Aime-Christian Why did you delete the associations with trip??

2021-02-09 06:40 UTC, James-nyagatare commented on src/middlewares/roleCheck.js
> +import jwt from 'jsonwebtoken';
@Mucyo-Aime-Christian  I don't think we need this middleware you can use the authentication middleware to check if the user exists and use isAllowed middleware to check if the user is the trip admin.

2021-02-10 05:51 UTC, harerakalex requested changes

2021-02-10 05:51 UTC, harerakalex commented on src/routes/userRoutes.js
> +
What did you change here, kindly avoid making your PR so noisy, Make sure when you touch the file you are going to make a valid change.

2021-02-10 05:51 UTC, harerakalex commented on src/services/accommodationService.js
> +      return accommodation || null;
Kindly take time and look into another service to see how others are being implemented.

2021-02-16 11:41 UTC, merged