room creation
atlp-rwanda/runners-bn-backend pull request #21
Opened 2021-02-18 07:19 UTC by Mucyo-Aime-Christian

## What does this PR do?

- create rooms in accommodation
- update room in accommodation
- delete room from accommodation
- view single and all rooms

## Description of Task to be completed?

-CRUD rooms
- test all endpoints
- document using swagger

## How should this be manually tested?

- clone the branch
- use postman
- write command ``npm run dev``

## Any background context you want to provide?

- N/A

## What are the relevant pivotal tracker stories?

-https://www.pivotaltracker.com/story/show/176861657

## Screenshots (if appropriate)

- N/A

## Questions:

2021-02-23 04:29 UTC, James-nyagatare reviewed
Welldone @Mucyo-Aime-Christian , please put in considerations the feedback I left on your PR

2021-02-23 04:29 UTC, James-nyagatare commented on src/controllers/roomController.js
> +      const accommodationExist = await AccommodationServices.findAccommodation(
@Mucyo-Aime-Christian, I suggest that this block along side it's if block can be removed and create it's own middleware to check if the accomodation exists as it is repeating it's self in this controller.

2021-02-23 04:29 UTC, James-nyagatare commented on src/controllers/roomController.js
> +    if (!accommodationExist) return Response.error(res, code.notFound, 'Accommodation does not exist');
Like here the block is repeating itself.

2021-02-23 04:29 UTC, James-nyagatare commented on src/controllers/roomController.js
> +    if (!accommodationExist) return Response.error(res, code.notFound, 'Accommodation does not exist');
same as here.

2021-02-23 19:42 UTC, James-nyagatare approved these changes

2021-02-25 13:31 UTC, harerakalex requested changes
Well done @Mucyo-Aime-Christian  Consider the below comment

2021-02-25 13:31 UTC, harerakalex commented on src/controllers/roomController.js
> +      if (roomImages.length === 0) return Response.error(res, code.notFound, 'please! provide a picture for your room');
is it necessary to update a room picture? @muchristian Kindly in while updating image is optional.

2021-02-25 15:19 UTC, harerakalex approved these changes

2021-02-25 15:19 UTC, merged