adding a badge
atlp-rwanda/runners-bn-backend pull request #3
Opened 2020-12-17 16:14 UTC by unadine

## What does this PR do?
Integrate TravisCI, coveralls and code climate with readme badge

## Description of Task to be completed?
adding badges to the readme

## How should this be manually tested?

## Any background context you want to provide?
Integrate TravisCI, coveralls and code climate with readme badge

## What are the relevant pivotal tracker stories?
Integrate TravisCI, coveralls and code climate with readme badge

## Screenshots (if appropriate)

## Questions:

2020-12-17 16:34 UTC, James-nyagatare reviewed
@unadine  what about the badge of Travis and coveralls?

2020-12-22 08:51 UTC, harerakalex requested changes
@unadine nice job

2020-12-22 08:51 UTC, harerakalex commented on README.md
> +<<<<<<< HEAD
@unadine kindly remove unnecessary stuff from this file.

2020-12-22 08:51 UTC, harerakalex commented on README.md
> +>>>>>>> chore(badges):Adding badges
This also is not needed

2020-12-22 09:03 UTC, harerakalex approved these changes

2020-12-22 09:04 UTC, merged